#!/usr/bin/env node
// Generates TypeScript types for the UI from the ENTITY SNAPSHOTS - the same
// files the automations are designed against - so the types cannot drift from
// the model the backend actually enforces.
//
//   node scripts/gen-types.mjs            -> writes the file named in kit.config.json
//   node scripts/gen-types.mjs --stdout   -> prints instead
//
// Product identifiers (entity prefix, interface base name, output path) come
// from kit.config.json. Nothing here is product-specific.
import fs from "node:fs";
import path from "node:path";
import { ROOT, config, ENTITY_TAGS } from "./kit-config.mjs";

const TYPES = path.join(ROOT, "snapshots/orbit/entity-types");
const OUT = path.join(ROOT, config.entities.typesInterfaceFile);
const BASE = config.entities.interfaceBaseName;   // e.g. "Icm"
const PRODUCT = config.product.name;              // e.g. "ICM"
const SNAP_CMD = `node scripts/ua.mjs snap-types ${ENTITY_TAGS.map((t) => `--tag ${t}`).join(" ")}`;

if (!fs.existsSync(TYPES)) {
  console.error(`error: no entity snapshots at ${path.relative(ROOT, TYPES)} - run \`${SNAP_CMD}\` first`);
  process.exit(1);
}

const files = fs.readdirSync(TYPES).filter((f) => f.endsWith(".json"));
const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

// json-schema property -> TS type, carrying the enum when the schema declares one
function tsType(prop) {
  if (Array.isArray(prop.oneOf) && prop.oneOf.every((o) => o.const !== undefined))
    return prop.oneOf.map((o) => JSON.stringify(o.const)).join(" | ");
  switch (prop.type) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "array": {
      const inner = prop.items ? tsType(prop.items) : "unknown";
      return inner.includes("|") ? `(${inner})[]` : `${inner}[]`;
    }
    case "object": return "Record<string, unknown>";
    default: return "unknown";
  }
}

const out = [];
out.push("// GENERATED by scripts/gen-types.mjs from snapshots/orbit/entity-types/.");
out.push("// Do not hand-edit: re-run the generator after the product team changes the model");
out.push(`// (\`${SNAP_CMD} && node scripts/gen-types.mjs\`).`);
out.push("//");
out.push("// Every record also carries these system fields, which the property schemas do NOT list:");
out.push("//   id, createdTime, modifiedTime, lastModifiedBy");
out.push("// A boolean that was never set is MISSING, not false - treat undefined as the default.");
out.push("");
out.push(`export interface ${BASE}RecordSystemFields {`);
out.push("  id: string;");
out.push(`  createdTime?: number;   // this is what 'createdAt' means in every ${PRODUCT} contract`);
out.push("  modifiedTime?: number;");
out.push("  lastModifiedBy?: number;");
out.push("}");
out.push("");

const entities = [];
for (const f of files.sort()) {
  const j = JSON.parse(fs.readFileSync(path.join(TYPES, f), "utf8"));
  const name = j.name || f.replace(/\.json$/, "");
  // Membership is by TAG, never by name (object names carry no product prefix).
  // Snapshots are already tag-filtered by `snap-types --tag`, so this is a guard
  // against a stray file rather than the primary filter.
  if (!(j.tags ?? []).some((t) => ENTITY_TAGS.includes(t))) continue;
  const sc = j.schema?.schema || j.schema || {};
  const props = sc.properties || {};
  const required = new Set(sc.required || []);
  const pk = j.metadata?.primaryKeyField;
  const uniqueKeyFields = j.metadata?.uniqueKeyFields || [];
  const iface = pascal(name);
  entities.push({ name, iface, pk });

  const head = [`\`${name}\` — storage object.`];
  if (pk) head.push(`PRIMARY KEY: \`${pk}\` (the record id IS this field).`);
  if (uniqueKeyFields.length)
    head.push(`UNIQUE INDEX on ${uniqueKeyFields.map((k) => `\`${k}\``).join(", ")} — a duplicate write is a raw E11000 at RUN time, so pre-check before writing.`);
  out.push(`/** ${head.join(" ")} */`);
  out.push(`export interface ${iface}Properties {`);
  for (const [k, v] of Object.entries(props)) {
    const notes = [];
    if (v.foreignKey?.reference) notes.push(`FK -> ${String(v.foreignKey.reference).replace("ENTITY_ID:", "")}`);
    if (v.uniqueKey || uniqueKeyFields.includes(k)) notes.push("UNIQUE (duplicate write = E11000 at RUN time)");
    if (k === pk) notes.push("PRIMARY KEY");
    if (notes.length) out.push(`  /** ${notes.join(" · ")} */`);
    out.push(`  ${k}${required.has(k) ? "" : "?"}: ${tsType(v)};`);
  }
  out.push("}");
  out.push(`export interface ${iface} extends ${BASE}RecordSystemFields {`);
  out.push(`  properties: ${iface}Properties;`);
  out.push("}");
  out.push("");
}

if (!entities.length) {
  console.error(`error: no snapshots carried any of the entity tags ${JSON.stringify(ENTITY_TAGS)} (kit.config.json).`);
  console.error(`       ${files.length} snapshot file(s) present. Either the tags are wrong or \`${SNAP_CMD}\` has not run.`);
  process.exit(1);
}

out.push(`/** Every ${PRODUCT} storage object, by its object_type string. */`);
out.push(`export type ${BASE}ObjectType =`);
for (const e of entities) out.push(`  | ${JSON.stringify(e.name)}`);
out[out.length - 1] += ";";
out.push("");
out.push(`export interface ${BASE}ObjectMap {`);
for (const e of entities) out.push(`  ${e.name}: ${e.iface};`);
out.push("}");
out.push("");

const text = out.join("\n") + "\n";
if (process.argv.includes("--stdout")) {
  process.stdout.write(text);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${entities.length} objects`);
}
