#!/usr/bin/env node
// CREATE helper for object (entity) types. This CHANGES the data model for
// everyone, so it is deliberately narrow: it only ever CREATES a new type from
// a compact spec file. It never updates, never retypes, never deletes.
// Use ua-schema.mjs to add fields to a type that already exists.
//
//   node scripts/ua-object.mjs plan   <spec.json>   print the body, call nothing
//   node scripts/ua-object.mjs create <spec.json>   POST /api/entity-type
//
// The full entity-type body has ~40 metadata keys and omitting them is
// untested (open question 11), so the body is expanded from the shape of
// `Period`, which was created this way and verified on orbit 2026-09-02.
//
// A spec file is the small half - the half a human should read:
//
//   {
//     "id": "Payee", "pluralName": "Payees",
//     "nameField": "name",
//     "uniqueKeyFields": ["employeeId"],
//     "properties": {
//       "employeeId": { "type": "string", "uniqueKey": true },
//       "hireDate":   { "type": "date" },
//       "userId":     { "type": "fk:USER" },
//       "periodId":   { "type": "fk:Period" }
//     }
//   }
//
// Tags come from kit.config.json and cannot be typed in a spec - membership is
// by TAG and a wrong tag silently orphans the object from every script here.
//
// Writes to PRODUCTION only with an explicit `--env tool` on the command line.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolveEnv } from "./env.mjs";
import { ENTITY_TAGS, TEST_TAG } from "./kit-config.mjs";
import { expandField, titleOf } from "./field-types.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const die = (m) => { console.error(`error: ${m}`); process.exit(1); };

const { env, baseUrl, cookie, args: argv } = resolveEnv({ write: true });

async function api(pathname, body) {
  const res = await fetch(baseUrl + pathname, {
    method: body === undefined ? "GET" : "POST",
    headers: { cookie: `_at=${cookie}`, "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  if (!res.ok) die(`${pathname} -> HTTP ${res.status}: ${text.slice(0, 600)}`);
  return text ? JSON.parse(text) : {};
}

function build(spec, { test }) {
  if (!spec.id) die("spec needs an `id`");
  if (!spec.properties || !Object.keys(spec.properties).length) die("spec needs `properties`");
  if (spec.tags) die("a spec may not carry `tags` - they come from kit.config.json");

  const properties = {}, layout = {}, order = [];
  const dateFields = [], filterableFields = [], referenceKeys = [], searchableFields = [];
  const required = [];

  for (const [name, f] of Object.entries(spec.properties)) {
    const { prop, reference, lookup, isDate } = expandField(name, f, die);
    if (f.searchable) searchableFields.push(name);
    if (name === (spec.nameField || "name")) prop.nameField = true;
    if (f.required) required.push(name);

    properties[name] = prop;
    order.push(name);
    if (prop.filterable) filterableFields.push(name);
    if (isDate) dateFields.push(name);
    if (reference) referenceKeys.push({ key: `properties.${name}`, referenceType: reference });
    if (lookup) layout[name] = lookup;
  }

  const nameField = spec.nameField || "name";
  if (!properties[nameField]) die(`nameField "${nameField}" is not one of the properties`);
  for (const k of spec.uniqueKeyFields || []) {
    if (!properties[k]) die(`uniqueKeyFields names "${k}", which is not a property`);
  }

  const jsonSchema = { type: "object", properties, ...(required.length ? { required } : {}) };

  return {
    id: spec.id,
    name: spec.name || spec.id,
    pluralName: spec.pluralName || `${spec.id}s`,
    lcName: (spec.name || spec.id).toLowerCase(),
    description: spec.description || "",
    tags: test ? [TEST_TAG] : [...ENTITY_TAGS],
    input: { type: "SCHEMA_AND_LAYOUT", dynamic: false, layout: { "ui:order": order, ...layout }, schema: jsonSchema },
    schema: { type: "SCHEMA", dynamic: false, schema: jsonSchema },
    metadata: {
      auditable: true,
      autoGeneratedFields: [],
      cacheable: false,
      captureActivity: true,
      captureReferences: false,
      captureReporting: true,
      dateFields,
      deployable: false,
      encryptedFields: [],
      external: false,
      filterableFields,
      graphType: "LEGACY_MDM",
      hasTimeSeriesRecords: true,
      hashedFields: [],
      includeInDependency: false,
      nameField,
      partFields: [],
      piiFields: spec.piiFields || [],
      primaryKeyField: "",
      referenceKeys,
      scdType2Enabled: false,
      schemaValidationEnabled: true,
      searchableFields,
      sessionBackedStorageEnabled: false,
      skipConfigSyncIfModified: false,
      skipDeletedEntityBackup: false,
      skipIndexLimitValidation: false,
      skipPermissionCheckForAggregation: false,
      skipPermissionsFilter: false,
      skipReportingEventsOrdering: false,
      skipRoutineLoad: false,
      skipTotalHitsInAggregation: false,
      skipVersionIncrementOnUpdate: false,
      storeDetails: { store: "MONGO", uniqueKeySupported: true },
      supportsDistinctValues: false,
      supportsWebhook: false,
      syncFromSourceCustomer: false,
      translationsEnabled: false,
      uniqueKeyFields: spec.uniqueKeyFields || [],
      urlValidationEnabledFields: [],
      useCachedEntityStoreForAutomations: false,
      userLevelEncryption: false,
      vectorFields: [],
      versioningEnabled: true,
    },
  };
}

const [cmd, file, ...rest] = argv;
if (!cmd || !file) die("usage: ua-object.mjs plan|create <spec.json> [--test] [--env orbit|tool]");
const test = rest.includes("--test");
const spec = JSON.parse(fs.readFileSync(path.resolve(file), "utf8"));
const body = build(spec, { test });

if (cmd === "plan") {
  console.log(JSON.stringify(body, null, 2));
  process.exit(0);
}
if (cmd !== "create") die(`unknown command "${cmd}"`);

const existing = await fetch(`${baseUrl}/api/entity-type?entityType=${encodeURIComponent(body.id)}`, {
  headers: { cookie: `_at=${cookie}` },
}).then((r) => (r.ok ? r.text() : ""));
if (existing && existing.includes(`"id"`) && existing.includes(body.id)) {
  die(`object type "${body.id}" already exists - this script only CREATES. Use ua-schema.mjs to add fields.`);
}

const out = await api("/api/entity-type", body);
console.log(`created ${body.id} on ${env}  tags=${JSON.stringify(body.tags)}  fields=${Object.keys(spec.properties).length}`);
console.log(`  uniqueKeyFields=${JSON.stringify(body.metadata.uniqueKeyFields)}  nameField=${body.metadata.nameField}`);
console.log(`  server returned id=${out.id ?? "(none)"} version=${out.version ?? "(none)"}`);
console.log(`next: node scripts/ua.mjs snap-types --tag ${test ? TEST_TAG : ENTITY_TAGS[0]}`);
