// GENERATED by scripts/gen-types.mjs from snapshots/orbit/entity-types/.
// Do not hand-edit: re-run the generator after the product team changes the model
// (`node scripts/ua.mjs snap-types --tag icm && node scripts/gen-types.mjs`).
//
// Every record also carries these system fields, which the property schemas do NOT list:
//   id, createdTime, modifiedTime, lastModifiedBy
// A boolean that was never set is MISSING, not false - treat undefined as the default.

export interface IcmRecordSystemFields {
  id: string;
  createdTime?: number;   // this is what 'createdAt' means in every ICM contract
  modifiedTime?: number;
  lastModifiedBy?: number;
}

/** `Period` — storage object. UNIQUE INDEX on `name` — a duplicate write is a raw E11000 at RUN time, so pre-check before writing. */
export interface PeriodProperties {
  /** UNIQUE (duplicate write = E11000 at RUN time) */
  name: string;
  periodType: string;
  startDate: number;
  endDate: number;
  status: string;
  /** FK -> Period */
  parentPeriodId?: string;
}
export interface Period extends IcmRecordSystemFields {
  properties: PeriodProperties;
}

/** `icmPeriod` — storage object. UNIQUE INDEX on `name` — a duplicate write is a raw E11000 at RUN time, so pre-check before writing. */
export interface IcmPeriodProperties {
  /** UNIQUE (duplicate write = E11000 at RUN time) */
  name: string;
  periodType: string;
  startDate: number;
  endDate: number;
  status: string;
  /** FK -> icmPeriod */
  parentPeriodId?: string;
}
export interface IcmPeriod extends IcmRecordSystemFields {
  properties: IcmPeriodProperties;
}

/** Every ICM storage object, by its object_type string. */
export type IcmObjectType =
  | "Period"
  | "icmPeriod";

export interface IcmObjectMap {
  Period: Period;
  icmPeriod: IcmPeriod;
}

